version: "3.9"

services:
  db:
    image: postgres:16
    container_name: parking_db
    restart: always
    environment:
      POSTGRES_USER: deploy
      POSTGRES_PASSWORD: deploy123
      POSTGRES_DB: parking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
